const Routes = {
  SplashScreen: "SplashScreen",
  Authenticated: "Authenticated",
  notAuthenticated: "notAuthenticated",
  Auth: "Auth",
  OnBoarding: "OnBoarding",
  Home: "Home",
  Login: "Login",
  Logout: "Logout",
  SignUp: "SignUp",
  ForgotPassword: "ForgotPassword",
  Profile: "Profile",
  Nearby: "Nearby",
  Search: "Search",
  Appointment: "Appointment",
  Career: "Career",
  ViewSalons: "ViewSalons",
  VerifyNumber: "VerifyNumber",
  VerifyOtp: "VerifyOtp",
  Filter: "Filter",
  OrderHistoryStack: "OrderHistoryStack",
  OrderHistoryAdminStack: "OrderHistoryAdminStack",
  OrderHistory: "OrderHistory",
  OrderHistoryAdmin: "OrderHistoryAdmin",
  OrderMedicine: "OrderMedicine",
  OrderDetails: "OrderDetails",
  TryOn: "TryOn",
  FilterSalons: "FilterSalons",
};
export default Routes;
